export const configKeys = {
    HTTP_SERVER_PORT: 'APP_PORT',
    APP_ENV: 'APP_ENV',
    SOCKET_PORT: 'SOCKET_PORT',
    JWT_SECRET: 'JWT_SECRET',

    JWT_EXPIRES: 'JWT_EXPIRES',

    KAFKA_HOST: 'KAFKA_URI',
    KAFKA_MECHANISM: 'KAFKA_MECHANISM',
    KAFKA_PORT: 'KAFKA_PORT',
    KAFKA_USER: 'KAFKA_USER',
    KAFKA_PASSWORD: 'KAFKA_PASS',
    KAFKA_DB: 'KAFKA_DB',
    KAFKA_EX: 'KAFKA_EX',
    KAFKA_ANALYSIS_MESSAGE_GROUP: 'KAFKA_ANALYSIS_MESSAGE_GROUP',
    KAFKA_ANALYSIS_MESSAGE_TOPIC: 'KAFKA_ANALYSIS_MESSAGE_TOPIC',

    API_USERS: "API_USERS",
    API_MESSAGES: "API_MESSAGES",
    DOC_USER: 'DOC_USER',
    DOC_PASS: 'DOC_PASS',


    // HEADER_USER_ID: 'HEADER_USER_ID',
    // HEADER_IS_ADMIN: 'HEADER_IS_ADMIN',
};